// config/schemas/leads.ts
import { z } from 'zod';

// Define the schema for the structured data (the "Artifact")
export const LeadsSchema = z.object({
    leads: z.array(
        z.object({
            id: z.number().describe("Unique ID for the lead."),
            name: z.string().describe("Full name of the prospect."),
            score: z.number().describe("Lead score from 1 to 100."),
            status: z.enum(['New', 'Contacted', 'Qualified', 'Unqualified']).describe("Current qualification status."),
            source: z.string().describe("Marketing channel the lead came from."),
        }).describe("A single lead record."),
    ).describe("A list of relevant leads generated by the AI."),
});

export type LeadsArtifact = z.infer<typeof LeadsSchema>;